
language: node_js
node_js: 6
git:
  depth: 5
cache:
  directories:
  - "./node_modules"
script:
- npm run lint
- npm run test:integration
- npm run countLOC:details
after_script:
- npm run coverage
- npm run countLOC:details
- npm start
